app:
  scheduler:
    cron: "*/10 * * * * *"
    fixed-rate: 5000
    initial-delay: 1000
    fixed-delay: 3000

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false